### ISSUE TITLE
Support custom filters

### ISSUE THREAD

**Issue by shredlocker** [finn-no/charcoal-ios#114]
There is no way for people to define their own filter setup. Maybe we should introduce a config file system which lets users define their own filter keys and values in stead of hard coding the filter config.

**Comment by osanoj** [comment]
To use this library you have to supply your own implementation of `FilterDataSource`, how that is built and from what is up to whoever uses it. Like in `DemoFilterRootViewControllerHelper`.

Or are you thinking of config files for the FINN specific filter builder?

**Comment by shredlocker** [comment]
I was thinking of config files for the specific filter builder, yes. Instead of using public enums to define the markets and the filter keys, we could use config files to define these things together with all the range parameters etc.

**Comment by 3lvis** [comment]
Old task, closing, reopen if needed.
