### ISSUE TITLE
Avoid base classes (ListViewController)

### ISSUE THREAD

**Issue by 3lvis** [finn-no/charcoal-ios#76]

**Comment by osanoj** [comment]
Removed in https://github.com/finn-no/charcoal-ios/pull/85

**Comment by 3lvis** [comment]
Should we close this then?

**Comment by osanoj** [comment]
Was just about to 😄

**Comment by 3lvis** [comment]
![flash](https://media.giphy.com/media/3oriNYQX2lC6dfW2Ji/giphy.gif)
