### ISSUE TITLE
Consider switching from double tap to two-finger double-tap to exit component

### ISSUE THREAD

**Issue by 3lvis** [finn-no/charcoal-ios#78]

**Comment by scanf** [comment]
Would also be nice to mention how you exit. Took me a few minutes to navigate back to the menu when running the demo. In FinniversKit there is a toast that show up at least once and says `Double tap to dismiss`.

**Comment by osanoj** [comment]
Yes, some guidance about how to exit the views should be added 👍

**Comment by 3lvis** [comment]
Old task, closing, reopen if needed.
